"""initial schema

Revision ID: 3f71182154a7
Revises: bb4dd034469d
Create Date: 2026-05-06 00:01:41.376704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f71182154a7'
down_revision = 'bb4dd034469d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
