"""initial schema

Revision ID: 4688d8fd3948
Revises: 3f71182154a7
Create Date: 2026-05-06 20:06:43.042424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4688d8fd3948'
down_revision = '3f71182154a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
