"""initial schema

Revision ID: bb4dd034469d
Revises: ecd23a48e079
Create Date: 2026-05-04 03:18:42.946527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4dd034469d'
down_revision = 'ecd23a48e079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
