"""initial schema

Revision ID: ce047cf7c540
Revises: 72163008561c
Create Date: 2026-05-04 02:02:22.755332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce047cf7c540'
down_revision = '72163008561c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
