"""enrollment_requests cascade delete training

Revision ID: dd77ae3091ef
Revises: a1b2c3d4e5f6
Create Date: 2026-05-30 22:57:24.882581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd77ae3091ef'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('enrollment_requests_training_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainings', ['training_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('enrollment_requests_training_id_fkey'), 'trainings', ['training_id'], ['id'])

    # ### end Alembic commands ###
