"""initial schema

Revision ID: ecd23a48e079
Revises: ce047cf7c540
Create Date: 2026-05-04 02:27:58.214133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd23a48e079'
down_revision = 'ce047cf7c540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
